name: Build and deploy
run-name: ${{ github.actor }} - Build and deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build
        env:
          GATSBY_WEBSITE_HOSTNAME: https://trycalmr.com
          GATSBY_STRIPE_PUBLIC_KEY: pk_live_51PdZVqCSMlpgjECRHtH15CLT2Q2fdn5faGSPUrUnGdEwffHMuNsNLuU7olWduyZfRAWQnpWtchled4zCmT9cIk4j00oNyOrM9w
          GATSBY_SHOPIFY_STORE_DOMAIN: https://calmrsupps.myshopify.com
          GATSBY_SHOPIFY_PUBLIC_ACCESS_TOKEN: fbdbe2ed192dcc7faada6059ca9fef38
      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: "./public"
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: b289c5b5-7077-4041-9202-77a98cca91ce
